config/routes.rb
Rails.application.routes.draw do
  resources :tracks do
      member do
          get :play
      end
  end
  resources :labels
  resources :albums do
      member do
          get :play
      end
  end
  resources :album_groups
  resources :artists
  resources :secondary_genres
  resources :genres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
      belongs_to :album_group
      belongs_to :artist
      belongs_to :label
      belongs_to :genre
      has_many :tracks

      def play
          tracks.each do |track|
              track.play
          end
      end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy, :play]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def play
      @album.play
      redirect_to @album
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.fetch(:album, {})
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(album) do |f| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @album.name %></h2>
<table>
    <tr><td>added</td><td><%= @album.added  %></td></tr>
    <tr><td>album_group</td><td><%= link_to @album.album_group.name, @album.album_group  %></td></tr>
    <tr><td>albumstatus</td><td><%= @album.albumstatus  %></td></tr>
    <tr><td>artist</td><td><%= link_to @album.artist.name, @album.artist  %></td></tr>
    <tr><td>beets_id</td><td><%= @album.beets_id  %></td></tr>
    <tr><td>catalognum</td><td><%= @album.catalognum  %></td></tr>
    <tr><td>comp</td><td><%= @album.comp  %></td></tr>
    <tr><td>day</td><td><%= @album.day  %></td></tr>
    <tr><td>disctotal</td><td><%= @album.disctotal  %></td></tr>
    <tr><td>genre</td><td><%=link_to @album.genre.name, @album.genre  %></td></tr>
    <tr><td>label</td><td><%= link_to @album.label.name, @album.label  %></td></tr>
    <tr><td>language</td><td><%= @album.language  %></td></tr>
    <tr><td>mb_albumid</td><td><%= @album.mb_albumid  %></td></tr>
    <tr><td>mb_releasegroupid</td><td><%= @album.mb_releasegroupid  %></td></tr>
    <tr><td>month</td><td><%= @album.month  %></td></tr>
    <tr><td>tracktotal</td><td><%= @album.tracktotal  %></td></tr>
    <tr><td>original_day</td><td><%= @album.original_day  %></td></tr>
    <tr><td>original_month</td><td><%= @album.original_month  %></td></tr>
    <tr><td>original_year</td><td><%= @album.original_year  %></td></tr>
    <tr><td>year</td><td><%= @album.year  %></td></tr>
</table>
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

<h3>Tracks</h3>
<ul>
    <% @album.tracks.each do |track| %>
    <li><%= link_to track.name, track %> <%= track.mb_trackid %><%= link_to 'play', play_track_path(track)%></li>
    <% end %>
</ul>